apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consumer-data-pvc
  namespace: ecommerce
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi